saberTxt = "Saber is one of the seven normal Servant classes summoned for the Holy Grail War. Servants placed within this class are agile and powerful melee warriors and it is commonly assumed to be the best class overall, with high ratings in all categories. It is one of the three Knight classes, together with Lancer and Archer, and also possesses the Riding skill like the Rider class."

archerTxt = "Archer, Knight of the Bow and Heroic Spirit of the Bow, is one of the Three Knight Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants placed within this Class excel in possessing powerful Great Weapons, are able to act as highly effective scouts, and are frequently Heroic Spirits from the Age of Gods when magecraft was still commonplace. The qualifying condition for the Heroic Spirits is not attributes, but instead the possession of powerful projectile weapons or special abilities related to projectile weapons."

riderTxt = "Rider, Mounted Knight and Heroic Spirit of the Mount, is one of the Four Cavalry Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants placed within this Class are those known for riding mounts, whether living beasts or human constructs, during their lives."

lancerTxt = "Lancer, Knight of the Lance and Heroic Spirit of the Lance, is one of the Three Knight Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants placed within this class, many of which are Heroic Spirits who were knights, are very agile, display excellent close combat skills, show proficiency in hit-and-run tactics that capitalize on range and speed, and are skilled with long-range melee weapons such as spears and lances."

casterTxt = "Caster, Magus and Heroic Spirit of Spells and Sorcery, is one of the Four Cavalry Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants placed within this Class are usually adept in magecraft, and the only qualifying condition is the mastery of sorceries of the highest caliber compared to the specific parameter requirements of the other classes."

berserkerTxt = "Berserkers, Mad Warrior and Heroic Spirit of Berserk Rage, is one of the Four Cavalry Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants placed within this Class are always Heroic Spirits who have gone berserk during battle at least once in their lifetime. This trait allows them to use the special ability Mad Enhancement, which trades their consciousness and sanity for a large power boost."

assassinTxt = "Assassin, Silent Killer and Heroic Spirit of Assassinations, is one of the Four Cavalry Classes among the seven standard Servant classes summoned for the Holy Grail War. Servants of this Class are skilled at operating covertly, stealthy, and silently. This class is one of the weaker classes at fighting; as its members possess low attributes due to not having glorious legends as heroes, it instead specializes in killing Masters rather than Servants."